### ISSUE TITLE
Bundling ffmpeg.js Causes Node Out of Memory Errors

### ISSUE THREAD

**Issue by 509dave16** [limistah/react-video-trimmer#1]
Hey,  @limistah ! The issue described in the subject is a problem in general. And I was hoping you may have found a solution to this in your work on this package. I have been attempting to bundle `ffmpeg.js` in my Expo project. But Node always runs out of memory. I don't know if you have any experience with Expo. I was looking through your solution to see if you were treating the `ffmpeg.js` imports in some special way in your babel configuration, etc...

**Comment by limistah** [comment]
In this project, no ffmpeg.js is bundled with it.
It uses a sister library that I created for `ffmpeg.js` and could be found here: https://limistah.github.io/ffmpeg-webworker/

Do let me know if you still have any concerns about loading `ffmpeg.js`
